#!/usr/bin/env bash

set -e

GID=3434 # circleci

for d in "$@"; do
  find "$d" \
    ! \( \
      -group $GID \
      -a -perm -g+rwX  \
    \) \
    -exec chgrp $GID {} \; \
    -exec chmod g+rwX {} \;
  # setuid,setgid *on directories only*
  find "$d" \
    \( \
        -type d \
        -a ! -perm -6000  \
    \) \
    -exec chmod +6000 {} \;
done
