name: build rasterframes scala
description: build rasterframes scala
inputs: 
  skip_tests:
    description: 'Skip Scala Tests? true or false'
    default: 'false'
runs:
  using: "composite"
  steps:
        - uses: coursier/cache-action@v6
        - name: Configure JDK
          uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: 8
            cache: sbt
        - name: Compile Scala
          shell: bash
          run: make compile-scala

        - name: Test Scale
          if: inputs.skip_tests == 'false'
          shell: bash
          run: make test-scala

        - name: Build FatJar
          shell: bash
          run: make build-scala

        # - name: Collect artifacts
        #   if: ${{ failure() }}
        #   shell: bash
        #   run: |
        #     mkdir -p /tmp/core_dumps
        #     ls -lh /tmp
        #     cp core.* *.hs /tmp/core_dumps/ 2> /dev/null || true
        #     cp ./core/*.log /tmp/core_dumps/ 2> /dev/null || true
        #     cp -r /tmp/hsperfdata* /tmp/*.hprof /tmp/core_dumps/ 2> /dev/null || true
        #     cp repo/core/core/* /tmp/core_dumps/ 2> /dev/null || true