name: Continuous Integration

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:

  build-scala:
    runs-on: ubuntu-20.04
    container:
      image: osgeo/gdal:ubuntu-small-3.6.2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Scala Build Tools
        uses: ./.github/actions/init-scala-env

      - name: Install make
        run: sudo apt-get install -y make

      - name: Compile Scala Project
        run: make compile-scala

      - name: Test Scala Project
        # python/* branches are not supposed to change scala code, trust them
        if: ${{ !startsWith(github.event.inputs.from_branch, 'python/') }}
        run: make test-scala

      - name: Build Spark Assembly
        shell: bash
        run: make build-scala

      - name: Cache Spark Assembly
        uses: actions/cache@v3
        with:
          path: ./python/pyrasterframes/jars/*
          key: dist-${{ github.sha }}

  build-python:
    # scala/* branches are not supposed to change python code, trust them
    if: ${{ !startsWith(github.event.inputs.from_branch, 'scala/') }}
    runs-on: ubuntu-20.04
    container:
      image: osgeo/gdal:ubuntu-small-3.6.2
    needs: build-scala

    strategy:
      matrix:
        python: [ "3.8" ]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: ./.github/actions/init-python-env
        with:
          python_version: ${{ matrix.python }}

      - name: Install make
        run: sudo apt-get install -y make

      - name: Static checks
        shell: bash
        run: make lint-python

      - uses: actions/cache@v3
        with:
          path: ./python/pyrasterframes/jars/*
          key: dist-${{ github.sha }}

      - name: Run tests
        shell: bash
        run: make test-python-quick

  publish:
    name: Publish Artifacts
    needs: [ build-scala, build-python ]
    runs-on: ubuntu-20.04
    if: (github.event_name != 'pull_request') && startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Scala Build Tools
        uses: ./.github/actions/init-scala-env

      - name: Install make
        run: sudo apt-get install -y make

      - name: Publish JARs to GitHub Packages
        shell: bash
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: make publish-scala

      - uses: ./.github/actions/init-python-env
        with:
          python_version: "3.8"

      - name: Build Python whl
        shell: bash
        run: make build-python


# TODO: Where does this go, do we need it?
#      - name: upload artefacts
#        uses: ./.github/actions/upload_artefacts

# TODO: Where does this go, do we need it?
#      - uses: actions/cache@v3
#        with:
#          path: ./python/pyrasterframes/jars/*
#          key: dist-${{ github.sha }}

# TODO: Where does this go?
#      - name: upload wheel
#        working-directory: dist
#        shell: bash
#        run:
